### ISSUE TITLE
How to make it work with router-view?

### ISSUE THREAD

**Issue by bruceyongli** [chrisvfritz/prerender-spa-plugin-vue-demo#1]
Thanks for your one-page demo! I tried with multiple pages and it didn't render the content to each page. Cloud you please show me how to use your package with multiple routes?

**Comment by chrisvfritz** [comment]
Here's an example of [the relevant config](https://github.com/chrisvfritz/vue-workshop/blob/master/build/webpack.prod.conf.js#L83-L93) for a multi-page app. Let me know if that helps. 😃

**Comment by danikane** [comment]
@chrisvfritz 
Hi, I keep getting this error on every single route ('/', '/about' etc..) during "npm run build" using the above config:
http://pastebin.com/RT6mww6n

Project is generated with vue-cli, using webpack and vue-router.

My routes are exported like this:
http://pastebin.com/EJxyeYCp

Then imported in main.js:
`import navConfig from './appRoutes'`

```
const router = new VueRouter({
  mode: 'history',
  routes: navConfig.navRoutes
})
```
Any leads?
Thanks in advance :)

update: tried a new vue-cli webpack boilerplate and it prerenders just fine ... Digging in my project now.

**Comment by danikane** [comment]
Got it, doesn't like Vuetify for some reason...
As soon as I do in main.js:
```
import Vuetify from 'vuetify'
```
it fails.

But using:
```
import 'core-js/es6/promise'
```
does it right.

**Comment by chrisvfritz** [comment]
Thanks for the update!
